apiVersion: v1
kind: Pod
metadata:
   name: mypod
   labels:
     app: Demo
     env: test
spec:
   containers:
      - name: nginx
        image: nginx
        ports:
          - name: http
            containerPort: 80
            protocol: TCP
