apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: hellocron
spec:
  schedule: "*/1 * * * *"
  jobTemplate:
    spec:
      template:
        spec:   
          containers:
          - name: hello-cont
            image: busybox
            args:
            - /bin/sh
            - -c
            - date; echo hello from kube cluseer
          restartPolicy: OnFailure 
