apiVersion: v1
kind: Pod
metadata: 
  name: nginx-centos-pod
spec:
  containers:
    - name: my-nginx-container
      image: nginx
    - name: my-centos-container
      image: centos
      command: ["/bin/sh", "-c", "while : ;do curl http://localhost:80/; sleep 3; done"]
