apiVersion: v1
kind: Pod
metadata:
  labels:
    app: my-dep
  name: my-dep
  namespace: default
spec:
  containers:
  - image: nginx:1.9.1
    imagePullPolicy: Always
    name: my-dep
    resources: {}
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: default-token-z8c9n
      readOnly: true
  dnsPolicy: ClusterFirst
  nodeName: clm-pun-t634bo
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: default
  serviceAccountName: default
  terminationGracePeriodSeconds: 30
  volumes:
  - name: default-token-z8c9n
    secret:
      defaultMode: 420
      secretName: default-token-z8c9n
