apiVersion: v1
kind: Pod
metadata:
  name: memory-demo
  labels:
    type: demo
    env: dev
  namespace: k8tasks
spec:
  containers:
  - name: memory-demo
    image: polinux/stress
    resources:
      requests:
        memory: 100Mi
      limits:
        memory: 200Mi
    command: ["stress"]
    args: ["--vm", "1", "--vm-bytes", "250M", "--vm-hang", "1"]

