apiVersion: v1
kind: Pod
metadata:
  name: cpu-demo
  labels:
    env: dev
    test: cpu
  namespace: k8tasks
spec:
  containers:
  - name: cpu-demo
    image: vish/stress
    resources:
      limits:
        cpu: "1" 
    args:
    - -cpus
    - "2"
