apiVersion: v1
kind: Pod
metadata:
  name: command-demo
  labels: 
    purpose: command-args
spec:
  containers:
  - name: command-demo
    image: debian
    command: ["prientenv"]
    args: ["HOSTNAME","KUBERNETES_PORT"]
  restartPolicy: OnFailure
