apiVersion: v1
kind: Pod
metadata:
  name: downward-api-env
  labels:
    app: downward-api-env
    env: dev
  namespace: k8tasks
spec:
  volumes:
  - name: downward-api-vol
    downwardAPI:
      items:
      - path: "labels"
        fieldRef:
          fieldPath: metadata.labels
      - path: "namespace"
        fieldRef:
          fieldPath: metadata.namespace   
  containers:
  - name: downward-api-env
    image: k8s.gcr.io/busybox
    command: ["sh","-c"]
    volumeMounts:
    - name: downward-api-vol
      mountPath: /etc/podinfo
    args:
    - while true; do
          echo -en '\n';
          printenv MY_NODE_NAME MY_POD_NAME MY_POD_NAMESPACE;
          printenv MY_POD_IP MY_POD_SERVICE_ACCOUNT;
          sleep 10;
        done;
    env:
    - name: NODE_NAME
      valueFrom:
        fieldRef:
          fieldPath: spec.nodeName
    - name: POD_NAMESPACE
      valueFrom:
        fieldRef:
          fieldPath: metadata.namespace
    - name: POD_NAME
      valueFrom:
        fieldRef:
          fieldPath: metadata.name   
