apiVersion: v1
kind: Pod
metadata:
  name: qos-burstable-demo
  labels:
    type: demo
    env: dev
  namespace: k8tasks
spec:
  containers:
  - name: qos-burstable-demo
    image: polinux/stress
   # QoS=Burstable as cpu or meoery resources are specified
    resources:
      requests:
        memory: 100Mi
        cpu: "500m"
      limits:
        memory: 150Mi
        cpu: "1"
    command: ["stress"]
    args: ["--vm", "1", "--vm-bytes", "100M", "--vm-hang", "1"]

