apiVersion: v1
kind: Pod
metadata:
  name: qos-besteffortsdemo
  labels:
    type: demo
    env: dev
  namespace: k8tasks
spec:
  containers:
  - name: qos-bestefforts-demo
    image: polinux/stress
   # QoS=BestEfforts as cpu andr meoery resources are not specified
    command: ["stress"]
    args: ["--vm", "1", "--vm-bytes", "100M", "--vm-hang", "1"]

