apiVersion: v1
kind: Pod
metadata:
  name: qos-guranted-demo
  labels:
    type: demo
    env: dev
  namespace: k8tasks
spec:
  containers:
  - name: qos-guranted-demo
    image: polinux/stress
   # QoS=Gurantes as request and limit of memory and cup are same
    resources:
      requests:
        memory: 150Mi
        cpu: "1"
      limits:
        memory: 150Mi
        cpu: "1"
    command: ["stress"]
    args: ["--vm", "1", "--vm-bytes", "100M", "--vm-hang", "1"]

