apiVersion: v1
kind: Service
metadata:
  name: mysql-svc
  labels:
    name: mysql-svc
    app: demo
spec:
  ports:
     - port: 3306
       name: mysql-port
       targetPort: 3306
  selector:
    name: mysql
    app: demo 
