apiVersion: batch/v1
kind: Job
metadata:
  name: my-job
  labels:
    app: my-job
spec:
  backoffLimit: 4
  template:
    metadata:
      name: my-job-pod
    spec:
      containers:
      - name: my-job-pod
        image: perl
        command: ["perl",  "-Mbignum=bpi", "-wle", "print bpi(2000)"]
      restartPolicy: OnFailure

