apiVersion: v1
kind: PersistentVolume
metadata:
  name: my-pv
  labels:
    env: dev
    task: pvc
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
  - ReadWriteOnce
  hostPath:
    path: "/mnt/data"
