apiVersion: v1
kind: Pod
metadata:
  name: my-pvc-pod
  labels:
    env: dev
    task: pvc-demo
spec:
  containers:
  - name: my-pvc-pod
    image: nginx
    ports:
    - containerPort: 80
      name: "http-server"
    volumeMounts:
    - name: my-pvc-storage
      mountPath: "/usr/share/nginx/html"
  volumes:
  - name: my-pvc-storage
    persistentVolumeClaim:
      claimName: task-pvc-claim

