apiVersion: v1
kind: PersistentVolume
metadata:
  name: test-pv
  labels:
    env: dev
    task: test-pvc
spec:
  storageClassName: slow
  capacity:
    storage: 10Gi
  accessModes:
  - ReadOnlyMany
  hostPath:
    path: "/mnt/abc"
