apiVersion: v1
kind: Pod
metadata:
  name: tcp-liveness
  labels:
    test: tcp-livenessprobe
spec:
  containers:
  - name: tcp-liveness-container
    image:  k8s.gcr.io/goproxy:0.1
    ports:
    - containerPort: 8080
    livenessProbe:
      tcpSocket:
        port: 8080
      initialDelaySeconds: 5
      periodSeconds: 20
    readinessProbe:
      tcpSocket:
        port: 8080
      initialDelaySeconds: 5
      periodSeconds: 20


          
