apiVersion: v1
kind: Pod
metadata:
  name: security-context-demo
  labels:
    app: security-context-demo
    env: dev
  namespace: k8tasks
spec:
  securityContext:
    runAsGroup: 2000
    runAsUser: 1000
    #fsGroup: 2000
  volumes:
  - name: sec-ctx-vol
    emptyDir: {}
  containers:
  - name: security-context-demo
    image: gcr.io/google-samples/node-hello:1.0
    volumeMounts: 
    - name: sec-ctx-vol
      mountPath: /data/demo
    securityContext:
      allowPrivilegeEscalation: false

