apiVersion: v1
kind: Pod
metadata:
  name: kuard-configmap
spec:
  containers:
  - name: kuard-configmap-container
    image: gcr.io/kuar-demo/kuard-amd64:1
    imagePullPolicy: Always
    command:
      - "/kuard"
      - "$(EXTRA_PARAM)"
    env:
    - name: ANOTHER_PARAM
      valueFrom: 
        configMapKeyRef:
          name: my-config
          key: another-param
    - name: EXTRA_PARAM
      valueFrom:
        configMapKeyRef:
          name: my-config
          key: extra-param
    volumeMounts:
    - name: kuard-config-volume
      mountPath: /config
  volumes:
  - name: kuard-config-volume
    configMap:
      name:  my-config 
