apiVersion: v1
kind: Pod
metadata:
  name: kaurd-secret
  labels:
    test: secret
spec:
  containers:
  - name: kuard-secret-container
    image: gcr.io/kuar-demo/kuard-amd64:1
    imagePullPolicy: Always
    volumeMounts:
    - name: kuard-secret-volume
      mountPath: "/tls"
      readOnly: true
  imagePullSecrets:
  - name: my-image-pull-secret
  volumes:
  - name: kuard-secret-volume
    secret:
      secretName: kaurd-tls

