apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  creationTimestamp: 2018-09-05T08:58:55Z
  generation: 1
  labels:
    app: task-secret
  name: task-secret
  namespace: default
  resourceVersion: "5428484"
  selfLink: /apis/extensions/v1beta1/namespaces/default/deployments/task-secret
  uid: eb0c3204-b0e9-11e8-8fed-0050568f3621
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: task-secret
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: task-secret
    spec:
      containers:
      - image: nginx
        imagePullPolicy: Always
        name: nginx
        env:
        - name: UserName1
          valueFrom:
             secretKeyRef:
               key: UserName
               name: task-secret
        - name: Password1
          valueFrom:
            secretKeyRef:
              key: Password
              name: task-secret 
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: 2018-09-05T08:59:20Z
    lastUpdateTime: 2018-09-05T08:59:20Z
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: 2018-09-05T08:58:55Z
    lastUpdateTime: 2018-09-05T08:59:20Z
    message: ReplicaSet "task-secret-8998448dd" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 1
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
